export const bugsData = [
  {
    id: 1,
    title: 'terrible bug',
    description: 'Pineapple button are not responding',
    solved: false,
    priority: 3,
    assignee: 'batman',
    reporter: 'superman',
  },
  {
    id: 2,
    title: 'Banana bug',
    description: 'problem with extension',
    solved: false,
    priority: 2,
    assignee: 'batman',
    reporter: 'batman',
  },
  {
    id: 3,
    title: 'Apple important bug',
    description: 'problem with styling',
    solved: true,
    priority: 1,
    assignee: 'robocop',
    reporter: 'robocop',
  },
  {
    id: 4,
    title: 'terrible Pineapple bug',
    description: 'button are not responding',
    solved: true,
    priority: 3,
    assignee: 'batman',
    reporter: 'superman',
  },
  {
    id: 5,
    title: 'not very bad Orange bug',
    description: 'problem with extension',
    solved: false,
    priority: 2,
    assignee: 'batman',
    reporter: 'batman',
  },
  {
    id: 6,
    title: 'not important bug',
    description: 'problem with styling',
    solved: false,
    priority: 1,
    assignee: 'superman',
    reporter: 'robocop',
  },
  {
    id: 7,
    title: 'terrible Tomato bug',
    description: 'button are not responding',
    solved: true,
    priority: 3,
    assignee: 'batman',
    reporter: 'superman',
  },
  {
    id: 8,
    title: 'not very bad bug',
    description: 'problem with extension',
    solved: true,
    priority: 2,
    assignee: 'batman',
    reporter: 'batman',
  },
  {
    id: 9,
    title: 'not important bug',
    description: 'problem with styling',
    solved: false,
    priority: 1,
    assignee: 'superman',
    reporter: 'robocop',
  },
  {
    id: 10,
    title: 'terrible bug',
    description: 'button are not responding',
    solved: false,
    priority: 3,
    assignee: 'batman',
    reporter: 'superman',
  },
  {
    id: 11,
    title: 'not very bad bug',
    description: 'problem with extension',
    solved: false,
    priority: 2,
    assignee: 'batman',
    reporter: 'batman',
  },
  {
    id: 12,
    title: 'not Tomato bug',
    description: 'problem with styling',
    solved: false,
    priority: 1,
    assignee: 'superman',
    reporter: 'robocop',
  },
  {
    id: 13,
    title: 'terrible bug',
    description: 'button are not responding',
    solved: false,
    priority: 3,
    assignee: 'batman',
    reporter: 'superman',
  },
  {
    id: 14,
    title: 'not Tomato bad bug',
    description: 'problem with extension',
    solved: false,
    priority: 2,
    assignee: 'batman',
    reporter: 'batman',
  },
  {
    id: 15,
    title: 'not important bug',
    description: 'problem with styling',
    solved: true,
    priority: 1,
    assignee: 'superman',
    reporter: 'robocop',
  },
  {
    id: 16,
    title: 'Banana bug',
    description: 'button are not responding',
    solved: false,
    priority: 3,
    assignee: 'batman',
    reporter: 'superman',
  },
  {
    id: 17,
    title: 'not very bad bug',
    description: 'problem with extension',
    solved: false,
    priority: 2,
    assignee: 'robocop',
    reporter: 'batman',
  },
  {
    id: 18,
    title: 'not important bug',
    description: 'problem with styling',
    solved: false,
    priority: 1,
    assignee: 'superman',
    reporter: 'robocop',
  },
  {
    id: 19,
    title: 'not Apple bad bug',
    description: 'problem with extension',
    solved: true,
    priority: 2,
    assignee: 'robocop',
    reporter: 'batman',
  },
  {
    id: 20,
    title: 'not Orange bug',
    description: 'problem with styling',
    solved: false,
    priority: 1,
    assignee: 'superman',
    reporter: 'robocop',
  },
];
